In [2]:
import pandas as pd
import os
import itertools
import numpy as np

In [31]:
df = pd.read_csv('monomer_data/monomers.csv')
df['mon_class'] = df['mon_class'].map(lambda x: str(x).lower())
df = df[df['mon_class'].isin(["cationic", "hydrophobic", "hydrophilic"])]
import json

encoding={v:chr(65+i) for i, v in enumerate(df["mon_abb"])}
json.dump(encoding, open("monomer_data/monomer_encoding.json", 'w'))

In [3]:
df = pd.read_csv('monomer_data/monomers.csv')
df['mon_class'] = df['mon_class'].map(lambda x: str(x).lower())
df = df[df['mon_class'].isin(["cationic", "hydrophobic", "hydrophilic"])]
df

,mon_class,mon_name,mon_abb,SMILES,min_class_wt,max_class_wt,min_mon_wt,max_mon_wt,increments,molar_mass,notes
0,cationic,(3-acrylamidopropyl)trimethylammonium chloride,Tma,C[N+](C)(C)CCCNC(=O)C=C,10.0,90.0,10.0,90.0,5.0,206.71,FOR ALL MONOMERS: the C=C double bond goes awa...
1,cationic,guanidinoethyl acrylamide,Aeg,[Cl-].NC(=[NH2+])NCCNC(=O)C=C,10.0,90.0,0.0,20.0,5.0,192.65,"Haven't used this yet, but I could try it movi..."
2,hydrophilic,4-acryloylmorpholine,Mo,C=CC(=O)N1CCOCC1,0.0,80.0,0.0,90.0,5.0,141.17,NaN
3,hydrophilic,N-(3-methoxypropyl)acrylamide,Mep,C=CC(=O)NCCCOC,0.0,80.0,0.0,90.0,5.0,143.18,NaN
4,hydrophobic,N-Isopropylacrylamide,Ni,CC(C)NC(=O)C=C,10.0,45.0,0.0,40.0,5.0,113.16,NaN
5,hydrophobic,N-phenylacrylamide,Phe,C=CC(=O)Nc1ccccc1,10.0,45.0,0.0,40.0,5.0,147.17,NaN
6,hydrophobic,N-dodecylacrylamide,Do,CCCCCCCCCCCCNC(=O)C=C,10.0,45.0,0.0,30.0,5.0,239.40,NaN
7,hydrophobic,N-butylacrylamide,Bam,CCCCOCNC(=O)C=C,10.0,45.0,0.0,40.0,5.0,127.18,NaN
8,hydrophobic,N-octylacrylamide,Oct,CCCCCCCCNC(=O)C=C,10.0,45.0,0.0,30.0,5.0,183.29,NaN
9,hydrophobic,oleylacrylamide,Olam,CCCCCCCC/C=C\CCCCCCCCNC(=O)C(=C),10.0,45.0,0.0,30.0,5.0,321.30,this is the only monomer that has a C=C bond t...
10,hydrophobic,N-(Butoxymethyl)acrylamide,Bmam,C=CC(=O)NCCCC,10.0,45.0,0.0,50.0,5.0,157.21,NaN
11,hydrophobic,"N-(1,1,3,3-Tetramethylbutyl)acrylamide",Tmb,CC(C)(C)CC(C)(C)NC(=O)C=C,10.0,45.0,0.0,30.0,5.0,183.29,NaN

In [4]:
monomer_classes = {}

for mon_class in df['mon_class'].unique():
    
    mon_class_dict = {}
    idx = (df['mon_class'] == mon_class)
    mon_class_dict['monomers'] = df[idx].mon_abb.tolist()
    mon_class_dict['min'] = df[idx].min_class_wt.unique().item()
    mon_class_dict['max'] = df[idx].max_class_wt.unique().item()
    mon_class_dict['increment'] = df[idx].increments.unique().item()
    monomer_classes[mon_class] = mon_class_dict

monomer_classes

{'cationic': {'monomers': ['Tma', 'Aeg'],
  'min': 10.0,
  'max': 90.0,
  'increment': 5.0},
 'hydrophilic': {'monomers': ['Mo', 'Mep'],
  'min': 0.0,
  'max': 80.0,
  'increment': 5.0},
 'hydrophobic': {'monomers': ['Ni',
   'Phe',
   'Do',
   'Bam',
   'Oct',
   'Olam',
   'Bmam',
   'Tmb'],
  'min': 10.0,
  'max': 45.0,
  'increment': 5.0}}

In [5]:
cols = ['mon_abb', 'SMILES', 'min_mon_wt', 'max_mon_wt', 'increments', 'molar_mass']
mon_df = df[cols].rename(columns={'min_mon_wt': 'min', 'max_mon_wt': 'max', 'increments': 'increment'})
monomer_properties = mon_df.set_index('mon_abb').T.to_dict('dict')
monomer_properties

{'Tma': {'SMILES': 'C[N+](C)(C)CCCNC(=O)C=C',
  'min': 10.0,
  'max': 90.0,
  'increment': 5.0,
  'molar_mass': 206.71},
 'Aeg': {'SMILES': '[Cl-].NC(=[NH2+])NCCNC(=O)C=C',
  'min': 0.0,
  'max': 20.0,
  'increment': 5.0,
  'molar_mass': 192.65},
 'Mo': {'SMILES': 'C=CC(=O)N1CCOCC1',
  'min': 0.0,
  'max': 90.0,
  'increment': 5.0,
  'molar_mass': 141.17},
 'Mep': {'SMILES': 'C=CC(=O)NCCCOC',
  'min': 0.0,
  'max': 90.0,
  'increment': 5.0,
  'molar_mass': 143.18},
 'Ni': {'SMILES': 'CC(C)NC(=O)C=C',
  'min': 0.0,
  'max': 40.0,
  'increment': 5.0,
  'molar_mass': 113.16},
 'Phe': {'SMILES': 'C=CC(=O)Nc1ccccc1',
  'min': 0.0,
  'max': 40.0,
  'increment': 5.0,
  'molar_mass': 147.17},
 'Do': {'SMILES': 'CCCCCCCCCCCCNC(=O)C=C',
  'min': 0.0,
  'max': 30.0,
  'increment': 5.0,
  'molar_mass': 239.4},
 'Bam': {'SMILES': 'CCCCOCNC(=O)C=C',
  'min': 0.0,
  'max': 40.0,
  'increment': 5.0,
  'molar_mass': 127.18},
 'Oct': {'SMILES': 'CCCCCCCCNC(=O)C=C',
  'min': 0.0,
  'max': 30.0,
  'increment': 5.0,
  'molar_mass': 183.29},
 'Olam': {'SMILES': 'CCCCCCCC/C=C\\CCCCCCCCNC(=O)C(=C)',
  'min': 0.0,
  'max': 30.0,
  'increment': 5.0,
  'molar_mass': 321.3},
 'Bmam': {'SMILES': 'C=CC(=O)NCCCC',
  'min': 0.0,
  'max': 50.0,
  'increment': 5.0,
  'molar_mass': 157.21},
 'Tmb': {'SMILES': 'CC(C)(C)CC(C)(C)NC(=O)C=C',
  'min': 0.0,
  'max': 30.0,
  'increment': 5.0,
  'molar_mass': 183.29}}

In [6]:
def get_range(key, dictionary):
    return range(int(dictionary[key]['min']), int(dictionary[key]['max']) + 1, int(dictionary[key]['increment']))

In [7]:
def product(*iterables, repeat=1):
    # product('ABCD', 'xy') → Ax Ay Bx By Cx Cy Dx Dy
    # product(range(2), repeat=3) → 000 001 010 011 100 101 110 111

    pools = [tuple(pool) for pool in iterables] * repeat

    result = [[]]
    for pool in pools:
        result = [x+[y] for x in result for y in pool]

    for prod in result:
        yield prod

In [8]:
def combinations(iterable, r):
    # combinations('ABCD', 2) → AB AC AD BC BD CD
    # combinations(range(4), 3) → 012 013 023 123

    pool = tuple(iterable)
    n = len(pool)
    if r > n:
        return
    indices = list(range(r))

    yield list(pool[i] for i in indices)
    while True:
        for i in reversed(range(r)):
            if indices[i] != i + n - r:
                break
        else:
            return
        indices[i] += 1
        for j in range(i+1, r):
            indices[j] = indices[j-1] + 1
        yield list(pool[i] for i in indices)

In [9]:
def generate_weights(monomer_ranges, target):
    # Generate all possible combinations using itertools.product
    possible_combinations = list(product(*monomer_ranges))
    
    # Filter combinations to ensure the sum equals 100%
    valid_combinations = [combo for combo in possible_combinations if sum(combo) == target]
    
    return valid_combinations

In [10]:
def generate_monomer_combinations(monomers, limit = None):
    
    all_combinations = []

    if limit is None:
        r_upper = len(monomers)
    else:
        r_upper = limit
    
    for r in range(1, r_upper + 1):
        all_combinations.extend(combinations(monomers, r))
    
    return all_combinations

In [11]:
monomer_class_ranges = [get_range('cationic', monomer_classes), get_range('hydrophilic', monomer_classes), get_range('hydrophobic', monomer_classes)]

In [12]:
monomer_class_distributions = generate_weights(monomer_class_ranges, 100)
monomer_class_distributions

[[10, 45, 45],
 [10, 50, 40],
 [10, 55, 35],
 [10, 60, 30],
 [10, 65, 25],
 [10, 70, 20],
 [10, 75, 15],
 [10, 80, 10],
 [15, 40, 45],
 [15, 45, 40],
 [15, 50, 35],
 [15, 55, 30],
 [15, 60, 25],
 [15, 65, 20],
 [15, 70, 15],
 [15, 75, 10],
 [20, 35, 45],
 [20, 40, 40],
 [20, 45, 35],
 [20, 50, 30],
 [20, 55, 25],
 [20, 60, 20],
 [20, 65, 15],
 [20, 70, 10],
 [25, 30, 45],
 [25, 35, 40],
 [25, 40, 35],
 [25, 45, 30],
 [25, 50, 25],
 [25, 55, 20],
 [25, 60, 15],
 [25, 65, 10],
 [30, 25, 45],
 [30, 30, 40],
 [30, 35, 35],
 [30, 40, 30],
 [30, 45, 25],
 [30, 50, 20],
 [30, 55, 15],
 [30, 60, 10],
 [35, 20, 45],
 [35, 25, 40],
 [35, 30, 35],
 [35, 35, 30],
 [35, 40, 25],
 [35, 45, 20],
 [35, 50, 15],
 [35, 55, 10],
 [40, 15, 45],
 [40, 20, 40],
 [40, 25, 35],
 [40, 30, 30],
 [40, 35, 25],
 [40, 40, 20],
 [40, 45, 15],
 [40, 50, 10],
 [45, 10, 45],
 [45, 15, 40],
 [45, 20, 35],
 [45, 25, 30],
 [45, 30, 25],
 [45, 35, 20],
 [45, 40, 15],
 [45, 45, 10],
 [50, 5, 45],
 [50, 10, 40],
 [50, 15, 35],
 [50, 20, 30],
 [50, 25, 25],
 [50, 30, 20],
 [50, 35, 15],
 [50, 40, 10],
 [55, 0, 45],
 [55, 5, 40],
 [55, 10, 35],
 [55, 15, 30],
 [55, 20, 25],
 [55, 25, 20],
 [55, 30, 15],
 [55, 35, 10],
 [60, 0, 40],
 [60, 5, 35],
 [60, 10, 30],
 [60, 15, 25],
 [60, 20, 20],
 [60, 25, 15],
 [60, 30, 10],
 [65, 0, 35],
 [65, 5, 30],
 [65, 10, 25],
 [65, 15, 20],
 [65, 20, 15],
 [65, 25, 10],
 [70, 0, 30],
 [70, 5, 25],
 [70, 10, 20],
 [70, 15, 15],
 [70, 20, 10],
 [75, 0, 25],
 [75, 5, 20],
 [75, 10, 15],
 [75, 15, 10],
 [80, 0, 20],
 [80, 5, 15],
 [80, 10, 10],
 [85, 0, 15],
 [85, 5, 10],
 [90, 0, 10]]

In [13]:
monomer_combinations = {}
limits = {'hydrophobic': 3}

for key in monomer_classes.keys():
    if key in limits:
        monomer_combinations[key] = generate_monomer_combinations(monomer_classes[key]['monomers'], limits[key])
    else: 
        monomer_combinations[key] = generate_monomer_combinations(monomer_classes[key]['monomers'])
        
monomer_combinations

{'cationic': [['Tma'], ['Aeg'], ['Tma', 'Aeg']],
 'hydrophilic': [['Mo'], ['Mep'], ['Mo', 'Mep']],
 'hydrophobic': [['Ni'],
  ['Phe'],
  ['Do'],
  ['Bam'],
  ['Oct'],
  ['Olam'],
  ['Bmam'],
  ['Tmb'],
  ['Ni', 'Phe'],
  ['Ni', 'Do'],
  ['Ni', 'Bam'],
  ['Ni', 'Oct'],
  ['Ni', 'Olam'],
  ['Ni', 'Bmam'],
  ['Ni', 'Tmb'],
  ['Phe', 'Do'],
  ['Phe', 'Bam'],
  ['Phe', 'Oct'],
  ['Phe', 'Olam'],
  ['Phe', 'Bmam'],
  ['Phe', 'Tmb'],
  ['Do', 'Bam'],
  ['Do', 'Oct'],
  ['Do', 'Olam'],
  ['Do', 'Bmam'],
  ['Do', 'Tmb'],
  ['Bam', 'Oct'],
  ['Bam', 'Olam'],
  ['Bam', 'Bmam'],
  ['Bam', 'Tmb'],
  ['Oct', 'Olam'],
  ['Oct', 'Bmam'],
  ['Oct', 'Tmb'],
  ['Olam', 'Bmam'],
  ['Olam', 'Tmb'],
  ['Bmam', 'Tmb'],
  ['Ni', 'Phe', 'Do'],
  ['Ni', 'Phe', 'Bam'],
  ['Ni', 'Phe', 'Oct'],
  ['Ni', 'Phe', 'Olam'],
  ['Ni', 'Phe', 'Bmam'],
  ['Ni', 'Phe', 'Tmb'],
  ['Ni', 'Do', 'Bam'],
  ['Ni', 'Do', 'Oct'],
  ['Ni', 'Do', 'Olam'],
  ['Ni', 'Do', 'Bmam'],
  ['Ni', 'Do', 'Tmb'],
  ['Ni', 'Bam', 'Oct'],
  ['Ni', 'Bam', 'Olam'],
  ['Ni', 'Bam', 'Bmam'],
  ['Ni', 'Bam', 'Tmb'],
  ['Ni', 'Oct', 'Olam'],
  ['Ni', 'Oct', 'Bmam'],
  ['Ni', 'Oct', 'Tmb'],
  ['Ni', 'Olam', 'Bmam'],
  ['Ni', 'Olam', 'Tmb'],
  ['Ni', 'Bmam', 'Tmb'],
  ['Phe', 'Do', 'Bam'],
  ['Phe', 'Do', 'Oct'],
  ['Phe', 'Do', 'Olam'],
  ['Phe', 'Do', 'Bmam'],
  ['Phe', 'Do', 'Tmb'],
  ['Phe', 'Bam', 'Oct'],
  ['Phe', 'Bam', 'Olam'],
  ['Phe', 'Bam', 'Bmam'],
  ['Phe', 'Bam', 'Tmb'],
  ['Phe', 'Oct', 'Olam'],
  ['Phe', 'Oct', 'Bmam'],
  ['Phe', 'Oct', 'Tmb'],
  ['Phe', 'Olam', 'Bmam'],
  ['Phe', 'Olam', 'Tmb'],
  ['Phe', 'Bmam', 'Tmb'],
  ['Do', 'Bam', 'Oct'],
  ['Do', 'Bam', 'Olam'],
  ['Do', 'Bam', 'Bmam'],
  ['Do', 'Bam', 'Tmb'],
  ['Do', 'Oct', 'Olam'],
  ['Do', 'Oct', 'Bmam'],
  ['Do', 'Oct', 'Tmb'],
  ['Do', 'Olam', 'Bmam'],
  ['Do', 'Olam', 'Tmb'],
  ['Do', 'Bmam', 'Tmb'],
  ['Bam', 'Oct', 'Olam'],
  ['Bam', 'Oct', 'Bmam'],
  ['Bam', 'Oct', 'Tmb'],
  ['Bam', 'Olam', 'Bmam'],
  ['Bam', 'Olam', 'Tmb'],
  ['Bam', 'Bmam', 'Tmb'],
  ['Oct', 'Olam', 'Bmam'],
  ['Oct', 'Olam', 'Tmb'],
  ['Oct', 'Bmam', 'Tmb'],
  ['Olam', 'Bmam', 'Tmb']]}

In [14]:
polymer_combinations = list(product(*[monomer_combinations['cationic'], monomer_combinations['hydrophilic'], monomer_combinations['hydrophobic']]))
polymer_combinations

[[['Tma'], ['Mo'], ['Ni']],
 [['Tma'], ['Mo'], ['Phe']],
 [['Tma'], ['Mo'], ['Do']],
 [['Tma'], ['Mo'], ['Bam']],
 [['Tma'], ['Mo'], ['Oct']],
 [['Tma'], ['Mo'], ['Olam']],
 [['Tma'], ['Mo'], ['Bmam']],
 [['Tma'], ['Mo'], ['Tmb']],
 [['Tma'], ['Mo'], ['Ni', 'Phe']],
 [['Tma'], ['Mo'], ['Ni', 'Do']],
 [['Tma'], ['Mo'], ['Ni', 'Bam']],
 [['Tma'], ['Mo'], ['Ni', 'Oct']],
 [['Tma'], ['Mo'], ['Ni', 'Olam']],
 [['Tma'], ['Mo'], ['Ni', 'Bmam']],
 [['Tma'], ['Mo'], ['Ni', 'Tmb']],
 [['Tma'], ['Mo'], ['Phe', 'Do']],
 [['Tma'], ['Mo'], ['Phe', 'Bam']],
 [['Tma'], ['Mo'], ['Phe', 'Oct']],
 [['Tma'], ['Mo'], ['Phe', 'Olam']],
 [['Tma'], ['Mo'], ['Phe', 'Bmam']],
 [['Tma'], ['Mo'], ['Phe', 'Tmb']],
 [['Tma'], ['Mo'], ['Do', 'Bam']],
 [['Tma'], ['Mo'], ['Do', 'Oct']],
 [['Tma'], ['Mo'], ['Do', 'Olam']],
 [['Tma'], ['Mo'], ['Do', 'Bmam']],
 [['Tma'], ['Mo'], ['Do', 'Tmb']],
 [['Tma'], ['Mo'], ['Bam', 'Oct']],
 [['Tma'], ['Mo'], ['Bam', 'Olam']],
 [['Tma'], ['Mo'], ['Bam', 'Bmam']],
 [['Tma'], ['Mo'], ['Bam', 'Tmb']],
 [['Tma'], ['Mo'], ['Oct', 'Olam']],
 [['Tma'], ['Mo'], ['Oct', 'Bmam']],
 [['Tma'], ['Mo'], ['Oct', 'Tmb']],
 [['Tma'], ['Mo'], ['Olam', 'Bmam']],
 [['Tma'], ['Mo'], ['Olam', 'Tmb']],
 [['Tma'], ['Mo'], ['Bmam', 'Tmb']],
 [['Tma'], ['Mo'], ['Ni', 'Phe', 'Do']],
 [['Tma'], ['Mo'], ['Ni', 'Phe', 'Bam']],
 [['Tma'], ['Mo'], ['Ni', 'Phe', 'Oct']],
 [['Tma'], ['Mo'], ['Ni', 'Phe', 'Olam']],
 [['Tma'], ['Mo'], ['Ni', 'Phe', 'Bmam']],
 [['Tma'], ['Mo'], ['Ni', 'Phe', 'Tmb']],
 [['Tma'], ['Mo'], ['Ni', 'Do', 'Bam']],
 [['Tma'], ['Mo'], ['Ni', 'Do', 'Oct']],
 [['Tma'], ['Mo'], ['Ni', 'Do', 'Olam']],
 [['Tma'], ['Mo'], ['Ni', 'Do', 'Bmam']],
 [['Tma'], ['Mo'], ['Ni', 'Do', 'Tmb']],
 [['Tma'], ['Mo'], ['Ni', 'Bam', 'Oct']],
 [['Tma'], ['Mo'], ['Ni', 'Bam', 'Olam']],
 [['Tma'], ['Mo'], ['Ni', 'Bam', 'Bmam']],
 [['Tma'], ['Mo'], ['Ni', 'Bam', 'Tmb']],
 [['Tma'], ['Mo'], ['Ni', 'Oct', 'Olam']],
 [['Tma'], ['Mo'], ['Ni', 'Oct', 'Bmam']],
 [['Tma'], ['Mo'], ['Ni', 'Oct', 'Tmb']],
 [['Tma'], ['Mo'], ['Ni', 'Olam', 'Bmam']],
 [['Tma'], ['Mo'], ['Ni', 'Olam', 'Tmb']],
 [['Tma'], ['Mo'], ['Ni', 'Bmam', 'Tmb']],
 [['Tma'], ['Mo'], ['Phe', 'Do', 'Bam']],
 [['Tma'], ['Mo'], ['Phe', 'Do', 'Oct']],
 [['Tma'], ['Mo'], ['Phe', 'Do', 'Olam']],
 [['Tma'], ['Mo'], ['Phe', 'Do', 'Bmam']],
 [['Tma'], ['Mo'], ['Phe', 'Do', 'Tmb']],
 [['Tma'], ['Mo'], ['Phe', 'Bam', 'Oct']],
 [['Tma'], ['Mo'], ['Phe', 'Bam', 'Olam']],
 [['Tma'], ['Mo'], ['Phe', 'Bam', 'Bmam']],
 [['Tma'], ['Mo'], ['Phe', 'Bam', 'Tmb']],
 [['Tma'], ['Mo'], ['Phe', 'Oct', 'Olam']],
 [['Tma'], ['Mo'], ['Phe', 'Oct', 'Bmam']],
 [['Tma'], ['Mo'], ['Phe', 'Oct', 'Tmb']],
 [['Tma'], ['Mo'], ['Phe', 'Olam', 'Bmam']],
 [['Tma'], ['Mo'], ['Phe', 'Olam', 'Tmb']],
 [['Tma'], ['Mo'], ['Phe', 'Bmam', 'Tmb']],
 [['Tma'], ['Mo'], ['Do', 'Bam', 'Oct']],
 [['Tma'], ['Mo'], ['Do', 'Bam', 'Olam']],
 [['Tma'], ['Mo'], ['Do', 'Bam', 'Bmam']],
 [['Tma'], ['Mo'], ['Do', 'Bam', 'Tmb']],
 [['Tma'], ['Mo'], ['Do', 'Oct', 'Olam']],
 [['Tma'], ['Mo'], ['Do', 'Oct', 'Bmam']],
 [['Tma'], ['Mo'], ['Do', 'Oct', 'Tmb']],
 [['Tma'], ['Mo'], ['Do', 'Olam', 'Bmam']],
 [['Tma'], ['Mo'], ['Do', 'Olam', 'Tmb']],
 [['Tma'], ['Mo'], ['Do', 'Bmam', 'Tmb']],
 [['Tma'], ['Mo'], ['Bam', 'Oct', 'Olam']],
 [['Tma'], ['Mo'], ['Bam', 'Oct', 'Bmam']],
 [['Tma'], ['Mo'], ['Bam', 'Oct', 'Tmb']],
 [['Tma'], ['Mo'], ['Bam', 'Olam', 'Bmam']],
 [['Tma'], ['Mo'], ['Bam', 'Olam', 'Tmb']],
 [['Tma'], ['Mo'], ['Bam', 'Bmam', 'Tmb']],
 [['Tma'], ['Mo'], ['Oct', 'Olam', 'Bmam']],
 [['Tma'], ['Mo'], ['Oct', 'Olam', 'Tmb']],
 [['Tma'], ['Mo'], ['Oct', 'Bmam', 'Tmb']],
 [['Tma'], ['Mo'], ['Olam', 'Bmam', 'Tmb']],
 [['Tma'], ['Mep'], ['Ni']],
 [['Tma'], ['Mep'], ['Phe']],
 [['Tma'], ['Mep'], ['Do']],
 [['Tma'], ['Mep'], ['Bam']],
 [['Tma'], ['Mep'], ['Oct']],
 [['Tma'], ['Mep'], ['Olam']],
 [['Tma'], ['Mep'], ['Bmam']],
 [['Tma'], ['Mep'], ['Tmb']],
 [['Tma'], ['Mep'], ['Ni', 'Phe']],
 [['Tma'], ['Mep'], ['Ni', 'Do']],
 [['Tma'], ['Mep'], ['Ni', 'Bam']],
 [['Tma'], ['Mep'], ['Ni', 'Oct']],
 [['Tma'], ['Mep'], ['Ni', 'Olam']],
 [['Tma'], ['Mep'], ['Ni', 'Bmam']],
 [['Tma'], ['Mep'], ['Ni', 'Tmb']],
 [['Tma'], ['Mep'], ['Phe', 'Do']],
 [['Tma'], ['Mep'], ['Phe', 'Bam']],
 [['Tma'], ['Mep'], ['Phe', 'Oct']],
 [['Tma'], ['Mep'], ['Phe', 'Olam']],
 [['Tma'], ['Mep'], ['Phe', 'Bmam']],
 [['Tma'], ['Mep'], ['Phe', 'Tmb']],
 [['Tma'], ['Mep'], ['Do', 'Bam']],
 [['Tma'], ['Mep'], ['Do', 'Oct']],
 [['Tma'], ['Mep'], ['Do', 'Olam']],
 [['Tma'], ['Mep'], ['Do', 'Bmam']],
 [['Tma'], ['Mep'], ['Do', 'Tmb']],
 [['Tma'], ['Mep'], ['Bam', 'Oct']],
 [['Tma'], ['Mep'], ['Bam', 'Olam']],
 [['Tma'], ['Mep'], ['Bam', 'Bmam']],
 [['Tma'], ['Mep'], ['Bam', 'Tmb']],
 [['Tma'], ['Mep'], ['Oct', 'Olam']],
 [['Tma'], ['Mep'], ['Oct', 'Bmam']],
 [['Tma'], ['Mep'], ['Oct', 'Tmb']],
 [['Tma'], ['Mep'], ['Olam', 'Bmam']],
 [['Tma'], ['Mep'], ['Olam', 'Tmb']],
 [['Tma'], ['Mep'], ['Bmam', 'Tmb']],
 [['Tma'], ['Mep'], ['Ni', 'Phe', 'Do']],
 [['Tma'], ['Mep'], ['Ni', 'Phe', 'Bam']],
 [['Tma'], ['Mep'], ['Ni', 'Phe', 'Oct']],
 [['Tma'], ['Mep'], ['Ni', 'Phe', 'Olam']],
 [['Tma'], ['Mep'], ['Ni', 'Phe', 'Bmam']],
 [['Tma'], ['Mep'], ['Ni', 'Phe', 'Tmb']],
 [['Tma'], ['Mep'], ['Ni', 'Do', 'Bam']],
 [['Tma'], ['Mep'], ['Ni', 'Do', 'Oct']],
 [['Tma'], ['Mep'], ['Ni', 'Do', 'Olam']],
 [['Tma'], ['Mep'], ['Ni', 'Do', 'Bmam']],
 [['Tma'], ['Mep'], ['Ni', 'Do', 'Tmb']],
 [['Tma'], ['Mep'], ['Ni', 'Bam', 'Oct']],
 [['Tma'], ['Mep'], ['Ni', 'Bam', 'Olam']],
 [['Tma'], ['Mep'], ['Ni', 'Bam', 'Bmam']],
 [['Tma'], ['Mep'], ['Ni', 'Bam', 'Tmb']],
 [['Tma'], ['Mep'], ['Ni', 'Oct', 'Olam']],
 [['Tma'], ['Mep'], ['Ni', 'Oct', 'Bmam']],
 [['Tma'], ['Mep'], ['Ni', 'Oct', 'Tmb']],
 [['Tma'], ['Mep'], ['Ni', 'Olam', 'Bmam']],
 [['Tma'], ['Mep'], ['Ni', 'Olam', 'Tmb']],
 [['Tma'], ['Mep'], ['Ni', 'Bmam', 'Tmb']],
 [['Tma'], ['Mep'], ['Phe', 'Do', 'Bam']],
 [['Tma'], ['Mep'], ['Phe', 'Do', 'Oct']],
 [['Tma'], ['Mep'], ['Phe', 'Do', 'Olam']],
 [['Tma'], ['Mep'], ['Phe', 'Do', 'Bmam']],
 [['Tma'], ['Mep'], ['Phe', 'Do', 'Tmb']],
 [['Tma'], ['Mep'], ['Phe', 'Bam', 'Oct']],
 [['Tma'], ['Mep'], ['Phe', 'Bam', 'Olam']],
 [['Tma'], ['Mep'], ['Phe', 'Bam', 'Bmam']],
 [['Tma'], ['Mep'], ['Phe', 'Bam', 'Tmb']],
 [['Tma'], ['Mep'], ['Phe', 'Oct', 'Olam']],
 [['Tma'], ['Mep'], ['Phe', 'Oct', 'Bmam']],
 [['Tma'], ['Mep'], ['Phe', 'Oct', 'Tmb']],
 [['Tma'], ['Mep'], ['Phe', 'Olam', 'Bmam']],
 [['Tma'], ['Mep'], ['Phe', 'Olam', 'Tmb']],
 [['Tma'], ['Mep'], ['Phe', 'Bmam', 'Tmb']],
 [['Tma'], ['Mep'], ['Do', 'Bam', 'Oct']],
 [['Tma'], ['Mep'], ['Do', 'Bam', 'Olam']],
 [['Tma'], ['Mep'], ['Do', 'Bam', 'Bmam']],
 [['Tma'], ['Mep'], ['Do', 'Bam', 'Tmb']],
 [['Tma'], ['Mep'], ['Do', 'Oct', 'Olam']],
 [['Tma'], ['Mep'], ['Do', 'Oct', 'Bmam']],
 [['Tma'], ['Mep'], ['Do', 'Oct', 'Tmb']],
 [['Tma'], ['Mep'], ['Do', 'Olam', 'Bmam']],
 [['Tma'], ['Mep'], ['Do', 'Olam', 'Tmb']],
 [['Tma'], ['Mep'], ['Do', 'Bmam', 'Tmb']],
 [['Tma'], ['Mep'], ['Bam', 'Oct', 'Olam']],
 [['Tma'], ['Mep'], ['Bam', 'Oct', 'Bmam']],
 [['Tma'], ['Mep'], ['Bam', 'Oct', 'Tmb']],
 [['Tma'], ['Mep'], ['Bam', 'Olam', 'Bmam']],
 [['Tma'], ['Mep'], ['Bam', 'Olam', 'Tmb']],
 [['Tma'], ['Mep'], ['Bam', 'Bmam', 'Tmb']],
 [['Tma'], ['Mep'], ['Oct', 'Olam', 'Bmam']],
 [['Tma'], ['Mep'], ['Oct', 'Olam', 'Tmb']],
 [['Tma'], ['Mep'], ['Oct', 'Bmam', 'Tmb']],
 [['Tma'], ['Mep'], ['Olam', 'Bmam', 'Tmb']],
 [['Tma'], ['Mo', 'Mep'], ['Ni']],
 [['Tma'], ['Mo', 'Mep'], ['Phe']],
 [['Tma'], ['Mo', 'Mep'], ['Do']],
 [['Tma'], ['Mo', 'Mep'], ['Bam']],
 [['Tma'], ['Mo', 'Mep'], ['Oct']],
 [['Tma'], ['Mo', 'Mep'], ['Olam']],
 [['Tma'], ['Mo', 'Mep'], ['Bmam']],
 [['Tma'], ['Mo', 'Mep'], ['Tmb']],
 [['Tma'], ['Mo', 'Mep'], ['Ni', 'Phe']],
 [['Tma'], ['Mo', 'Mep'], ['Ni', 'Do']],
 [['Tma'], ['Mo', 'Mep'], ['Ni', 'Bam']],
 [['Tma'], ['Mo', 'Mep'], ['Ni', 'Oct']],
 [['Tma'], ['Mo', 'Mep'], ['Ni', 'Olam']],
 [['Tma'], ['Mo', 'Mep'], ['Ni', 'Bmam']],
 [['Tma'], ['Mo', 'Mep'], ['Ni', 'Tmb']],
 [['Tma'], ['Mo', 'Mep'], ['Phe', 'Do']],
 [['Tma'], ['Mo', 'Mep'], ['Phe', 'Bam']],
 [['Tma'], ['Mo', 'Mep'], ['Phe', 'Oct']],
 [['Tma'], ['Mo', 'Mep'], ['Phe', 'Olam']],
 [['Tma'], ['Mo', 'Mep'], ['Phe', 'Bmam']],
 [['Tma'], ['Mo', 'Mep'], ['Phe', 'Tmb']],
 [['Tma'], ['Mo', 'Mep'], ['Do', 'Bam']],
 [['Tma'], ['Mo', 'Mep'], ['Do', 'Oct']],
 [['Tma'], ['Mo', 'Mep'], ['Do', 'Olam']],
 [['Tma'], ['Mo', 'Mep'], ['Do', 'Bmam']],
 [['Tma'], ['Mo', 'Mep'], ['Do', 'Tmb']],
 [['Tma'], ['Mo', 'Mep'], ['Bam', 'Oct']],
 [['Tma'], ['Mo', 'Mep'], ['Bam', 'Olam']],
 [['Tma'], ['Mo', 'Mep'], ['Bam', 'Bmam']],
 [['Tma'], ['Mo', 'Mep'], ['Bam', 'Tmb']],
 [['Tma'], ['Mo', 'Mep'], ['Oct', 'Olam']],
 [['Tma'], ['Mo', 'Mep'], ['Oct', 'Bmam']],
 [['Tma'], ['Mo', 'Mep'], ['Oct', 'Tmb']],
 [['Tma'], ['Mo', 'Mep'], ['Olam', 'Bmam']],
 [['Tma'], ['Mo', 'Mep'], ['Olam', 'Tmb']],
 [['Tma'], ['Mo', 'Mep'], ['Bmam', 'Tmb']],
 [['Tma'], ['Mo', 'Mep'], ['Ni', 'Phe', 'Do']],
 [['Tma'], ['Mo', 'Mep'], ['Ni', 'Phe', 'Bam']],
 [['Tma'], ['Mo', 'Mep'], ['Ni', 'Phe', 'Oct']],
 [['Tma'], ['Mo', 'Mep'], ['Ni', 'Phe', 'Olam']],
 [['Tma'], ['Mo', 'Mep'], ['Ni', 'Phe', 'Bmam']],
 [['Tma'], ['Mo', 'Mep'], ['Ni', 'Phe', 'Tmb']],
 [['Tma'], ['Mo', 'Mep'], ['Ni', 'Do', 'Bam']],
 [['Tma'], ['Mo', 'Mep'], ['Ni', 'Do', 'Oct']],
 [['Tma'], ['Mo', 'Mep'], ['Ni', 'Do', 'Olam']],
 [['Tma'], ['Mo', 'Mep'], ['Ni', 'Do', 'Bmam']],
 [['Tma'], ['Mo', 'Mep'], ['Ni', 'Do', 'Tmb']],
 [['Tma'], ['Mo', 'Mep'], ['Ni', 'Bam', 'Oct']],
 [['Tma'], ['Mo', 'Mep'], ['Ni', 'Bam', 'Olam']],
 [['Tma'], ['Mo', 'Mep'], ['Ni', 'Bam', 'Bmam']],
 [['Tma'], ['Mo', 'Mep'], ['Ni', 'Bam', 'Tmb']],
 [['Tma'], ['Mo', 'Mep'], ['Ni', 'Oct', 'Olam']],
 [['Tma'], ['Mo', 'Mep'], ['Ni', 'Oct', 'Bmam']],
 [['Tma'], ['Mo', 'Mep'], ['Ni', 'Oct', 'Tmb']],
 [['Tma'], ['Mo', 'Mep'], ['Ni', 'Olam', 'Bmam']],
 [['Tma'], ['Mo', 'Mep'], ['Ni', 'Olam', 'Tmb']],
 [['Tma'], ['Mo', 'Mep'], ['Ni', 'Bmam', 'Tmb']],
 [['Tma'], ['Mo', 'Mep'], ['Phe', 'Do', 'Bam']],
 [['Tma'], ['Mo', 'Mep'], ['Phe', 'Do', 'Oct']],
 [['Tma'], ['Mo', 'Mep'], ['Phe', 'Do', 'Olam']],
 [['Tma'], ['Mo', 'Mep'], ['Phe', 'Do', 'Bmam']],
 [['Tma'], ['Mo', 'Mep'], ['Phe', 'Do', 'Tmb']],
 [['Tma'], ['Mo', 'Mep'], ['Phe', 'Bam', 'Oct']],
 [['Tma'], ['Mo', 'Mep'], ['Phe', 'Bam', 'Olam']],
 [['Tma'], ['Mo', 'Mep'], ['Phe', 'Bam', 'Bmam']],
 [['Tma'], ['Mo', 'Mep'], ['Phe', 'Bam', 'Tmb']],
 [['Tma'], ['Mo', 'Mep'], ['Phe', 'Oct', 'Olam']],
 [['Tma'], ['Mo', 'Mep'], ['Phe', 'Oct', 'Bmam']],
 [['Tma'], ['Mo', 'Mep'], ['Phe', 'Oct', 'Tmb']],
 [['Tma'], ['Mo', 'Mep'], ['Phe', 'Olam', 'Bmam']],
 [['Tma'], ['Mo', 'Mep'], ['Phe', 'Olam', 'Tmb']],
 [['Tma'], ['Mo', 'Mep'], ['Phe', 'Bmam', 'Tmb']],
 [['Tma'], ['Mo', 'Mep'], ['Do', 'Bam', 'Oct']],
 [['Tma'], ['Mo', 'Mep'], ['Do', 'Bam', 'Olam']],
 [['Tma'], ['Mo', 'Mep'], ['Do', 'Bam', 'Bmam']],
 [['Tma'], ['Mo', 'Mep'], ['Do', 'Bam', 'Tmb']],
 [['Tma'], ['Mo', 'Mep'], ['Do', 'Oct', 'Olam']],
 [['Tma'], ['Mo', 'Mep'], ['Do', 'Oct', 'Bmam']],
 [['Tma'], ['Mo', 'Mep'], ['Do', 'Oct', 'Tmb']],
 [['Tma'], ['Mo', 'Mep'], ['Do', 'Olam', 'Bmam']],
 [['Tma'], ['Mo', 'Mep'], ['Do', 'Olam', 'Tmb']],
 [['Tma'], ['Mo', 'Mep'], ['Do', 'Bmam', 'Tmb']],
 [['Tma'], ['Mo', 'Mep'], ['Bam', 'Oct', 'Olam']],
 [['Tma'], ['Mo', 'Mep'], ['Bam', 'Oct', 'Bmam']],
 [['Tma'], ['Mo', 'Mep'], ['Bam', 'Oct', 'Tmb']],
 [['Tma'], ['Mo', 'Mep'], ['Bam', 'Olam', 'Bmam']],
 [['Tma'], ['Mo', 'Mep'], ['Bam', 'Olam', 'Tmb']],
 [['Tma'], ['Mo', 'Mep'], ['Bam', 'Bmam', 'Tmb']],
 [['Tma'], ['Mo', 'Mep'], ['Oct', 'Olam', 'Bmam']],
 [['Tma'], ['Mo', 'Mep'], ['Oct', 'Olam', 'Tmb']],
 [['Tma'], ['Mo', 'Mep'], ['Oct', 'Bmam', 'Tmb']],
 [['Tma'], ['Mo', 'Mep'], ['Olam', 'Bmam', 'Tmb']],
 [['Aeg'], ['Mo'], ['Ni']],
 [['Aeg'], ['Mo'], ['Phe']],
 [['Aeg'], ['Mo'], ['Do']],
 [['Aeg'], ['Mo'], ['Bam']],
 [['Aeg'], ['Mo'], ['Oct']],
 [['Aeg'], ['Mo'], ['Olam']],
 [['Aeg'], ['Mo'], ['Bmam']],
 [['Aeg'], ['Mo'], ['Tmb']],
 [['Aeg'], ['Mo'], ['Ni', 'Phe']],
 [['Aeg'], ['Mo'], ['Ni', 'Do']],
 [['Aeg'], ['Mo'], ['Ni', 'Bam']],
 [['Aeg'], ['Mo'], ['Ni', 'Oct']],
 [['Aeg'], ['Mo'], ['Ni', 'Olam']],
 [['Aeg'], ['Mo'], ['Ni', 'Bmam']],
 [['Aeg'], ['Mo'], ['Ni', 'Tmb']],
 [['Aeg'], ['Mo'], ['Phe', 'Do']],
 [['Aeg'], ['Mo'], ['Phe', 'Bam']],
 [['Aeg'], ['Mo'], ['Phe', 'Oct']],
 [['Aeg'], ['Mo'], ['Phe', 'Olam']],
 [['Aeg'], ['Mo'], ['Phe', 'Bmam']],
 [['Aeg'], ['Mo'], ['Phe', 'Tmb']],
 [['Aeg'], ['Mo'], ['Do', 'Bam']],
 [['Aeg'], ['Mo'], ['Do', 'Oct']],
 [['Aeg'], ['Mo'], ['Do', 'Olam']],
 [['Aeg'], ['Mo'], ['Do', 'Bmam']],
 [['Aeg'], ['Mo'], ['Do', 'Tmb']],
 [['Aeg'], ['Mo'], ['Bam', 'Oct']],
 [['Aeg'], ['Mo'], ['Bam', 'Olam']],
 [['Aeg'], ['Mo'], ['Bam', 'Bmam']],
 [['Aeg'], ['Mo'], ['Bam', 'Tmb']],
 [['Aeg'], ['Mo'], ['Oct', 'Olam']],
 [['Aeg'], ['Mo'], ['Oct', 'Bmam']],
 [['Aeg'], ['Mo'], ['Oct', 'Tmb']],
 [['Aeg'], ['Mo'], ['Olam', 'Bmam']],
 [['Aeg'], ['Mo'], ['Olam', 'Tmb']],
 [['Aeg'], ['Mo'], ['Bmam', 'Tmb']],
 [['Aeg'], ['Mo'], ['Ni', 'Phe', 'Do']],
 [['Aeg'], ['Mo'], ['Ni', 'Phe', 'Bam']],
 [['Aeg'], ['Mo'], ['Ni', 'Phe', 'Oct']],
 [['Aeg'], ['Mo'], ['Ni', 'Phe', 'Olam']],
 [['Aeg'], ['Mo'], ['Ni', 'Phe', 'Bmam']],
 [['Aeg'], ['Mo'], ['Ni', 'Phe', 'Tmb']],
 [['Aeg'], ['Mo'], ['Ni', 'Do', 'Bam']],
 [['Aeg'], ['Mo'], ['Ni', 'Do', 'Oct']],
 [['Aeg'], ['Mo'], ['Ni', 'Do', 'Olam']],
 [['Aeg'], ['Mo'], ['Ni', 'Do', 'Bmam']],
 [['Aeg'], ['Mo'], ['Ni', 'Do', 'Tmb']],
 [['Aeg'], ['Mo'], ['Ni', 'Bam', 'Oct']],
 [['Aeg'], ['Mo'], ['Ni', 'Bam', 'Olam']],
 [['Aeg'], ['Mo'], ['Ni', 'Bam', 'Bmam']],
 [['Aeg'], ['Mo'], ['Ni', 'Bam', 'Tmb']],
 [['Aeg'], ['Mo'], ['Ni', 'Oct', 'Olam']],
 [['Aeg'], ['Mo'], ['Ni', 'Oct', 'Bmam']],
 [['Aeg'], ['Mo'], ['Ni', 'Oct', 'Tmb']],
 [['Aeg'], ['Mo'], ['Ni', 'Olam', 'Bmam']],
 [['Aeg'], ['Mo'], ['Ni', 'Olam', 'Tmb']],
 [['Aeg'], ['Mo'], ['Ni', 'Bmam', 'Tmb']],
 [['Aeg'], ['Mo'], ['Phe', 'Do', 'Bam']],
 [['Aeg'], ['Mo'], ['Phe', 'Do', 'Oct']],
 [['Aeg'], ['Mo'], ['Phe', 'Do', 'Olam']],
 [['Aeg'], ['Mo'], ['Phe', 'Do', 'Bmam']],
 [['Aeg'], ['Mo'], ['Phe', 'Do', 'Tmb']],
 [['Aeg'], ['Mo'], ['Phe', 'Bam', 'Oct']],
 [['Aeg'], ['Mo'], ['Phe', 'Bam', 'Olam']],
 [['Aeg'], ['Mo'], ['Phe', 'Bam', 'Bmam']],
 [['Aeg'], ['Mo'], ['Phe', 'Bam', 'Tmb']],
 [['Aeg'], ['Mo'], ['Phe', 'Oct', 'Olam']],
 [['Aeg'], ['Mo'], ['Phe', 'Oct', 'Bmam']],
 [['Aeg'], ['Mo'], ['Phe', 'Oct', 'Tmb']],
 [['Aeg'], ['Mo'], ['Phe', 'Olam', 'Bmam']],
 [['Aeg'], ['Mo'], ['Phe', 'Olam', 'Tmb']],
 [['Aeg'], ['Mo'], ['Phe', 'Bmam', 'Tmb']],
 [['Aeg'], ['Mo'], ['Do', 'Bam', 'Oct']],
 [['Aeg'], ['Mo'], ['Do', 'Bam', 'Olam']],
 [['Aeg'], ['Mo'], ['Do', 'Bam', 'Bmam']],
 [['Aeg'], ['Mo'], ['Do', 'Bam', 'Tmb']],
 [['Aeg'], ['Mo'], ['Do', 'Oct', 'Olam']],
 [['Aeg'], ['Mo'], ['Do', 'Oct', 'Bmam']],
 [['Aeg'], ['Mo'], ['Do', 'Oct', 'Tmb']],
 [['Aeg'], ['Mo'], ['Do', 'Olam', 'Bmam']],
 [['Aeg'], ['Mo'], ['Do', 'Olam', 'Tmb']],
 [['Aeg'], ['Mo'], ['Do', 'Bmam', 'Tmb']],
 [['Aeg'], ['Mo'], ['Bam', 'Oct', 'Olam']],
 [['Aeg'], ['Mo'], ['Bam', 'Oct', 'Bmam']],
 [['Aeg'], ['Mo'], ['Bam', 'Oct', 'Tmb']],
 [['Aeg'], ['Mo'], ['Bam', 'Olam', 'Bmam']],
 [['Aeg'], ['Mo'], ['Bam', 'Olam', 'Tmb']],
 [['Aeg'], ['Mo'], ['Bam', 'Bmam', 'Tmb']],
 [['Aeg'], ['Mo'], ['Oct', 'Olam', 'Bmam']],
 [['Aeg'], ['Mo'], ['Oct', 'Olam', 'Tmb']],
 [['Aeg'], ['Mo'], ['Oct', 'Bmam', 'Tmb']],
 [['Aeg'], ['Mo'], ['Olam', 'Bmam', 'Tmb']],
 [['Aeg'], ['Mep'], ['Ni']],
 [['Aeg'], ['Mep'], ['Phe']],
 [['Aeg'], ['Mep'], ['Do']],
 [['Aeg'], ['Mep'], ['Bam']],
 [['Aeg'], ['Mep'], ['Oct']],
 [['Aeg'], ['Mep'], ['Olam']],
 [['Aeg'], ['Mep'], ['Bmam']],
 [['Aeg'], ['Mep'], ['Tmb']],
 [['Aeg'], ['Mep'], ['Ni', 'Phe']],
 [['Aeg'], ['Mep'], ['Ni', 'Do']],
 [['Aeg'], ['Mep'], ['Ni', 'Bam']],
 [['Aeg'], ['Mep'], ['Ni', 'Oct']],
 [['Aeg'], ['Mep'], ['Ni', 'Olam']],
 [['Aeg'], ['Mep'], ['Ni', 'Bmam']],
 [['Aeg'], ['Mep'], ['Ni', 'Tmb']],
 [['Aeg'], ['Mep'], ['Phe', 'Do']],
 [['Aeg'], ['Mep'], ['Phe', 'Bam']],
 [['Aeg'], ['Mep'], ['Phe', 'Oct']],
 [['Aeg'], ['Mep'], ['Phe', 'Olam']],
 [['Aeg'], ['Mep'], ['Phe', 'Bmam']],
 [['Aeg'], ['Mep'], ['Phe', 'Tmb']],
 [['Aeg'], ['Mep'], ['Do', 'Bam']],
 [['Aeg'], ['Mep'], ['Do', 'Oct']],
 [['Aeg'], ['Mep'], ['Do', 'Olam']],
 [['Aeg'], ['Mep'], ['Do', 'Bmam']],
 [['Aeg'], ['Mep'], ['Do', 'Tmb']],
 [['Aeg'], ['Mep'], ['Bam', 'Oct']],
 [['Aeg'], ['Mep'], ['Bam', 'Olam']],
 [['Aeg'], ['Mep'], ['Bam', 'Bmam']],
 [['Aeg'], ['Mep'], ['Bam', 'Tmb']],
 [['Aeg'], ['Mep'], ['Oct', 'Olam']],
 [['Aeg'], ['Mep'], ['Oct', 'Bmam']],
 [['Aeg'], ['Mep'], ['Oct', 'Tmb']],
 [['Aeg'], ['Mep'], ['Olam', 'Bmam']],
 [['Aeg'], ['Mep'], ['Olam', 'Tmb']],
 [['Aeg'], ['Mep'], ['Bmam', 'Tmb']],
 [['Aeg'], ['Mep'], ['Ni', 'Phe', 'Do']],
 [['Aeg'], ['Mep'], ['Ni', 'Phe', 'Bam']],
 [['Aeg'], ['Mep'], ['Ni', 'Phe', 'Oct']],
 [['Aeg'], ['Mep'], ['Ni', 'Phe', 'Olam']],
 [['Aeg'], ['Mep'], ['Ni', 'Phe', 'Bmam']],
 [['Aeg'], ['Mep'], ['Ni', 'Phe', 'Tmb']],
 [['Aeg'], ['Mep'], ['Ni', 'Do', 'Bam']],
 [['Aeg'], ['Mep'], ['Ni', 'Do', 'Oct']],
 [['Aeg'], ['Mep'], ['Ni', 'Do', 'Olam']],
 [['Aeg'], ['Mep'], ['Ni', 'Do', 'Bmam']],
 [['Aeg'], ['Mep'], ['Ni', 'Do', 'Tmb']],
 [['Aeg'], ['Mep'], ['Ni', 'Bam', 'Oct']],
 [['Aeg'], ['Mep'], ['Ni', 'Bam', 'Olam']],
 [['Aeg'], ['Mep'], ['Ni', 'Bam', 'Bmam']],
 [['Aeg'], ['Mep'], ['Ni', 'Bam', 'Tmb']],
 [['Aeg'], ['Mep'], ['Ni', 'Oct', 'Olam']],
 [['Aeg'], ['Mep'], ['Ni', 'Oct', 'Bmam']],
 [['Aeg'], ['Mep'], ['Ni', 'Oct', 'Tmb']],
 [['Aeg'], ['Mep'], ['Ni', 'Olam', 'Bmam']],
 [['Aeg'], ['Mep'], ['Ni', 'Olam', 'Tmb']],
 [['Aeg'], ['Mep'], ['Ni', 'Bmam', 'Tmb']],
 [['Aeg'], ['Mep'], ['Phe', 'Do', 'Bam']],
 [['Aeg'], ['Mep'], ['Phe', 'Do', 'Oct']],
 [['Aeg'], ['Mep'], ['Phe', 'Do', 'Olam']],
 [['Aeg'], ['Mep'], ['Phe', 'Do', 'Bmam']],
 [['Aeg'], ['Mep'], ['Phe', 'Do', 'Tmb']],
 [['Aeg'], ['Mep'], ['Phe', 'Bam', 'Oct']],
 [['Aeg'], ['Mep'], ['Phe', 'Bam', 'Olam']],
 [['Aeg'], ['Mep'], ['Phe', 'Bam', 'Bmam']],
 [['Aeg'], ['Mep'], ['Phe', 'Bam', 'Tmb']],
 [['Aeg'], ['Mep'], ['Phe', 'Oct', 'Olam']],
 [['Aeg'], ['Mep'], ['Phe', 'Oct', 'Bmam']],
 [['Aeg'], ['Mep'], ['Phe', 'Oct', 'Tmb']],
 [['Aeg'], ['Mep'], ['Phe', 'Olam', 'Bmam']],
 [['Aeg'], ['Mep'], ['Phe', 'Olam', 'Tmb']],
 [['Aeg'], ['Mep'], ['Phe', 'Bmam', 'Tmb']],
 [['Aeg'], ['Mep'], ['Do', 'Bam', 'Oct']],
 [['Aeg'], ['Mep'], ['Do', 'Bam', 'Olam']],
 [['Aeg'], ['Mep'], ['Do', 'Bam', 'Bmam']],
 [['Aeg'], ['Mep'], ['Do', 'Bam', 'Tmb']],
 [['Aeg'], ['Mep'], ['Do', 'Oct', 'Olam']],
 [['Aeg'], ['Mep'], ['Do', 'Oct', 'Bmam']],
 [['Aeg'], ['Mep'], ['Do', 'Oct', 'Tmb']],
 [['Aeg'], ['Mep'], ['Do', 'Olam', 'Bmam']],
 [['Aeg'], ['Mep'], ['Do', 'Olam', 'Tmb']],
 [['Aeg'], ['Mep'], ['Do', 'Bmam', 'Tmb']],
 [['Aeg'], ['Mep'], ['Bam', 'Oct', 'Olam']],
 [['Aeg'], ['Mep'], ['Bam', 'Oct', 'Bmam']],
 [['Aeg'], ['Mep'], ['Bam', 'Oct', 'Tmb']],
 [['Aeg'], ['Mep'], ['Bam', 'Olam', 'Bmam']],
 [['Aeg'], ['Mep'], ['Bam', 'Olam', 'Tmb']],
 [['Aeg'], ['Mep'], ['Bam', 'Bmam', 'Tmb']],
 [['Aeg'], ['Mep'], ['Oct', 'Olam', 'Bmam']],
 [['Aeg'], ['Mep'], ['Oct', 'Olam', 'Tmb']],
 [['Aeg'], ['Mep'], ['Oct', 'Bmam', 'Tmb']],
 [['Aeg'], ['Mep'], ['Olam', 'Bmam', 'Tmb']],
 [['Aeg'], ['Mo', 'Mep'], ['Ni']],
 [['Aeg'], ['Mo', 'Mep'], ['Phe']],
 [['Aeg'], ['Mo', 'Mep'], ['Do']],
 [['Aeg'], ['Mo', 'Mep'], ['Bam']],
 [['Aeg'], ['Mo', 'Mep'], ['Oct']],
 [['Aeg'], ['Mo', 'Mep'], ['Olam']],
 [['Aeg'], ['Mo', 'Mep'], ['Bmam']],
 [['Aeg'], ['Mo', 'Mep'], ['Tmb']],
 [['Aeg'], ['Mo', 'Mep'], ['Ni', 'Phe']],
 [['Aeg'], ['Mo', 'Mep'], ['Ni', 'Do']],
 [['Aeg'], ['Mo', 'Mep'], ['Ni', 'Bam']],
 [['Aeg'], ['Mo', 'Mep'], ['Ni', 'Oct']],
 [['Aeg'], ['Mo', 'Mep'], ['Ni', 'Olam']],
 [['Aeg'], ['Mo', 'Mep'], ['Ni', 'Bmam']],
 [['Aeg'], ['Mo', 'Mep'], ['Ni', 'Tmb']],
 [['Aeg'], ['Mo', 'Mep'], ['Phe', 'Do']],
 [['Aeg'], ['Mo', 'Mep'], ['Phe', 'Bam']],
 [['Aeg'], ['Mo', 'Mep'], ['Phe', 'Oct']],
 [['Aeg'], ['Mo', 'Mep'], ['Phe', 'Olam']],
 [['Aeg'], ['Mo', 'Mep'], ['Phe', 'Bmam']],
 [['Aeg'], ['Mo', 'Mep'], ['Phe', 'Tmb']],
 [['Aeg'], ['Mo', 'Mep'], ['Do', 'Bam']],
 [['Aeg'], ['Mo', 'Mep'], ['Do', 'Oct']],

In [15]:
def monomer_class_ranges(monomer_class_in_poly, full_monomer_class):
    
    monomer_weight_ranges = []
    for mon in full_monomer_class:
        if mon in monomer_class_in_poly:
            monomer_weight_ranges.append(get_range(mon, monomer_properties))
        else:
            monomer_weight_ranges.append(range(0,1,5))

    return monomer_weight_ranges

In [16]:
def generate_polymer_weights(full_combo, polymer_combo, distribution):
    weights = []

    weights.append([[distribution]])
    
    for i in range(len(polymer_combo)):
        weights.append(generate_weights(monomer_class_ranges(polymer_combo[i], full_combo[i]), distribution[i]))
    return weights

In [17]:
def compute_mol(combo_list, flattened_full_combo, molar_masses):
    weights = np.array(combo_list[1:])

    weights = weights / molar_masses
    weights = weights / weights.sum()

    idx = weights.nonzero()    
    weights = weights[idx].tolist()

    combo_list.append(np.array(flattened_full_combo)[idx].tolist())
    combo_list.append([monomer_properties[mon]['SMILES'] for mon in np.array(flattened_full_combo)[idx]])
    combo_list.append(weights)

    return combo_list

In [18]:
# DEMO
# full_combo = [monomer_classes[key]['monomers'] for key in monomer_classes.keys()]
# flattened_full_combo = sum(full_combo,[])

# molar_masses = np.array([monomer_properties[mon]['molar_mass'] for mon in flattened_full_combo])


# polymer_combo = [['Tma', 'Aeg'], ['Mo'], ['Phe', 'Bam', 'Oct']]
# distribution = [15, 60, 25]
# generate_polymer_weights(full_combo, polymer_combo, distribution)

# [list(itertools.chain(*row)) for row in product(*generate_polymer_weights(full_combo,polymer_combo, distribution))]
# [compute_mol(list(itertools.chain(*row)), flattened_full_combo, molar_masses) for row in product(*generate_polymer_weights(full_combo,polymer_combo, distribution))]

In [19]:
full_combo = [monomer_classes[key]['monomers'] for key in monomer_classes.keys()]

flattened_full_combo = sum(full_combo,[])
molar_masses = np.array([monomer_properties[mon]['molar_mass'] for mon in flattened_full_combo])


col_names = full_combo.copy()
col_names.insert(0, ["class_distribution"])
col_names.append(["monomers"])
col_names.append(["SMILES"])
col_names.append(["mol_distribution"])

running_list = [sum(col_names,[])]

num = 1

for polymer_combo in polymer_combinations:
    print("Polymer Combination: " + str(num) + " / " + str(len(polymer_combinations)))
    num += 1
    for distribution in monomer_class_distributions:
        running_list.extend([compute_mol(list(itertools.chain(*row)), flattened_full_combo, molar_masses) 
                             for row in product(*generate_polymer_weights(full_combo, polymer_combo, distribution))])

Polymer Combination: 1 / 828
Polymer Combination: 2 / 828
Polymer Combination: 3 / 828
Polymer Combination: 4 / 828
Polymer Combination: 5 / 828
Polymer Combination: 6 / 828
Polymer Combination: 7 / 828
Polymer Combination: 8 / 828
Polymer Combination: 9 / 828
Polymer Combination: 10 / 828
Polymer Combination: 11 / 828
Polymer Combination: 12 / 828
Polymer Combination: 13 / 828
Polymer Combination: 14 / 828
Polymer Combination: 15 / 828
Polymer Combination: 16 / 828
Polymer Combination: 17 / 828
Polymer Combination: 18 / 828
Polymer Combination: 19 / 828
Polymer Combination: 20 / 828
Polymer Combination: 21 / 828
Polymer Combination: 22 / 828
Polymer Combination: 23 / 828
Polymer Combination: 24 / 828
Polymer Combination: 25 / 828
Polymer Combination: 26 / 828
Polymer Combination: 27 / 828
Polymer Combination: 28 / 828
Polymer Combination: 29 / 828
Polymer Combination: 30 / 828
Polymer Combination: 31 / 828
Polymer Combination: 32 / 828
Polymer Combination: 33 / 828
Polymer Combination: 34 / 828
Polymer Combination: 35 / 828
Polymer Combination: 36 / 828
Polymer Combination: 37 / 828
Polymer Combination: 38 / 828
Polymer Combination: 39 / 828
Polymer Combination: 40 / 828
Polymer Combination: 41 / 828
Polymer Combination: 42 / 828
Polymer Combination: 43 / 828
Polymer Combination: 44 / 828
Polymer Combination: 45 / 828
Polymer Combination: 46 / 828
Polymer Combination: 47 / 828
Polymer Combination: 48 / 828
Polymer Combination: 49 / 828
Polymer Combination: 50 / 828
Polymer Combination: 51 / 828
Polymer Combination: 52 / 828
Polymer Combination: 53 / 828
Polymer Combination: 54 / 828
Polymer Combination: 55 / 828
Polymer Combination: 56 / 828
Polymer Combination: 57 / 828
Polymer Combination: 58 / 828
Polymer Combination: 59 / 828
Polymer Combination: 60 / 828
Polymer Combination: 61 / 828
Polymer Combination: 62 / 828
Polymer Combination: 63 / 828
Polymer Combination: 64 / 828
Polymer Combination: 65 / 828
Polymer Combination: 66 / 828
Polymer Combination: 67 / 828
Polymer Combination: 68 / 828
Polymer Combination: 69 / 828
Polymer Combination: 70 / 828
Polymer Combination: 71 / 828
Polymer Combination: 72 / 828
Polymer Combination: 73 / 828
Polymer Combination: 74 / 828
Polymer Combination: 75 / 828
Polymer Combination: 76 / 828
Polymer Combination: 77 / 828
Polymer Combination: 78 / 828
Polymer Combination: 79 / 828
Polymer Combination: 80 / 828
Polymer Combination: 81 / 828
Polymer Combination: 82 / 828
Polymer Combination: 83 / 828
Polymer Combination: 84 / 828
Polymer Combination: 85 / 828
Polymer Combination: 86 / 828
Polymer Combination: 87 / 828
Polymer Combination: 88 / 828
Polymer Combination: 89 / 828
Polymer Combination: 90 / 828
Polymer Combination: 91 / 828
Polymer Combination: 92 / 828
Polymer Combination: 93 / 828
Polymer Combination: 94 / 828
Polymer Combination: 95 / 828
Polymer Combination: 96 / 828
Polymer Combination: 97 / 828
Polymer Combination: 98 / 828
Polymer Combination: 99 / 828
Polymer Combination: 100 / 828
Polymer Combination: 101 / 828
Polymer Combination: 102 / 828
Polymer Combination: 103 / 828
Polymer Combination: 104 / 828
Polymer Combination: 105 / 828
Polymer Combination: 106 / 828
Polymer Combination: 107 / 828
Polymer Combination: 108 / 828
Polymer Combination: 109 / 828
Polymer Combination: 110 / 828
Polymer Combination: 111 / 828
Polymer Combination: 112 / 828
Polymer Combination: 113 / 828
Polymer Combination: 114 / 828
Polymer Combination: 115 / 828
Polymer Combination: 116 / 828
Polymer Combination: 117 / 828
Polymer Combination: 118 / 828
Polymer Combination: 119 / 828
Polymer Combination: 120 / 828
Polymer Combination: 121 / 828
Polymer Combination: 122 / 828
Polymer Combination: 123 / 828
Polymer Combination: 124 / 828
Polymer Combination: 125 / 828
Polymer Combination: 126 / 828
Polymer Combination: 127 / 828
Polymer Combination: 128 / 828
Polymer Combination: 129 / 828
Polymer Combination: 130 / 828
Polymer Combination: 131 / 828
Polymer Combination: 132 / 828
Polymer Combination: 133 / 828
Polymer Combination: 134 / 828
Polymer Combination: 135 / 828
Polymer Combination: 136 / 828
Polymer Combination: 137 / 828
Polymer Combination: 138 / 828
Polymer Combination: 139 / 828
Polymer Combination: 140 / 828
Polymer Combination: 141 / 828
Polymer Combination: 142 / 828
Polymer Combination: 143 / 828
Polymer Combination: 144 / 828
Polymer Combination: 145 / 828
Polymer Combination: 146 / 828
Polymer Combination: 147 / 828
Polymer Combination: 148 / 828
Polymer Combination: 149 / 828
Polymer Combination: 150 / 828
Polymer Combination: 151 / 828
Polymer Combination: 152 / 828
Polymer Combination: 153 / 828
Polymer Combination: 154 / 828
Polymer Combination: 155 / 828
Polymer Combination: 156 / 828
Polymer Combination: 157 / 828
Polymer Combination: 158 / 828
Polymer Combination: 159 / 828
Polymer Combination: 160 / 828
Polymer Combination: 161 / 828
Polymer Combination: 162 / 828
Polymer Combination: 163 / 828
Polymer Combination: 164 / 828
Polymer Combination: 165 / 828
Polymer Combination: 166 / 828
Polymer Combination: 167 / 828
Polymer Combination: 168 / 828
Polymer Combination: 169 / 828
Polymer Combination: 170 / 828
Polymer Combination: 171 / 828
Polymer Combination: 172 / 828
Polymer Combination: 173 / 828
Polymer Combination: 174 / 828
Polymer Combination: 175 / 828
Polymer Combination: 176 / 828
Polymer Combination: 177 / 828
Polymer Combination: 178 / 828
Polymer Combination: 179 / 828
Polymer Combination: 180 / 828
Polymer Combination: 181 / 828
Polymer Combination: 182 / 828
Polymer Combination: 183 / 828
Polymer Combination: 184 / 828
Polymer Combination: 185 / 828
Polymer Combination: 186 / 828
Polymer Combination: 187 / 828
Polymer Combination: 188 / 828
Polymer Combination: 189 / 828
Polymer Combination: 190 / 828
Polymer Combination: 191 / 828
Polymer Combination: 192 / 828
Polymer Combination: 193 / 828
Polymer Combination: 194 / 828
Polymer Combination: 195 / 828
Polymer Combination: 196 / 828
Polymer Combination: 197 / 828
Polymer Combination: 198 / 828
Polymer Combination: 199 / 828
Polymer Combination: 200 / 828
Polymer Combination: 201 / 828
Polymer Combination: 202 / 828
Polymer Combination: 203 / 828
Polymer Combination: 204 / 828
Polymer Combination: 205 / 828
Polymer Combination: 206 / 828
Polymer Combination: 207 / 828
Polymer Combination: 208 / 828
Polymer Combination: 209 / 828
Polymer Combination: 210 / 828
Polymer Combination: 211 / 828
Polymer Combination: 212 / 828
Polymer Combination: 213 / 828
Polymer Combination: 214 / 828
Polymer Combination: 215 / 828
Polymer Combination: 216 / 828
Polymer Combination: 217 / 828
Polymer Combination: 218 / 828
Polymer Combination: 219 / 828
Polymer Combination: 220 / 828
Polymer Combination: 221 / 828
Polymer Combination: 222 / 828
Polymer Combination: 223 / 828
Polymer Combination: 224 / 828
Polymer Combination: 225 / 828
Polymer Combination: 226 / 828
Polymer Combination: 227 / 828
Polymer Combination: 228 / 828
Polymer Combination: 229 / 828
Polymer Combination: 230 / 828
Polymer Combination: 231 / 828
Polymer Combination: 232 / 828
Polymer Combination: 233 / 828
Polymer Combination: 234 / 828
Polymer Combination: 235 / 828
Polymer Combination: 236 / 828
Polymer Combination: 237 / 828
Polymer Combination: 238 / 828
Polymer Combination: 239 / 828
Polymer Combination: 240 / 828
Polymer Combination: 241 / 828
Polymer Combination: 242 / 828
Polymer Combination: 243 / 828
Polymer Combination: 244 / 828
Polymer Combination: 245 / 828
Polymer Combination: 246 / 828
Polymer Combination: 247 / 828
Polymer Combination: 248 / 828
Polymer Combination: 249 / 828
Polymer Combination: 250 / 828
Polymer Combination: 251 / 828
Polymer Combination: 252 / 828
Polymer Combination: 253 / 828
Polymer Combination: 254 / 828
Polymer Combination: 255 / 828
Polymer Combination: 256 / 828
Polymer Combination: 257 / 828
Polymer Combination: 258 / 828
Polymer Combination: 259 / 828
Polymer Combination: 260 / 828
Polymer Combination: 261 / 828
Polymer Combination: 262 / 828
Polymer Combination: 263 / 828
Polymer Combination: 264 / 828
Polymer Combination: 265 / 828
Polymer Combination: 266 / 828
Polymer Combination: 267 / 828
Polymer Combination: 268 / 828
Polymer Combination: 269 / 828
Polymer Combination: 270 / 828
Polymer Combination: 271 / 828
Polymer Combination: 272 / 828
Polymer Combination: 273 / 828
Polymer Combination: 274 / 828
Polymer Combination: 275 / 828
Polymer Combination: 276 / 828
Polymer Combination: 277 / 828
Polymer Combination: 278 / 828
Polymer Combination: 279 / 828
Polymer Combination: 280 / 828
Polymer Combination: 281 / 828
Polymer Combination: 282 / 828
Polymer Combination: 283 / 828
Polymer Combination: 284 / 828
Polymer Combination: 285 / 828
Polymer Combination: 286 / 828
Polymer Combination: 287 / 828
Polymer Combination: 288 / 828
Polymer Combination: 289 / 828
Polymer Combination: 290 / 828
Polymer Combination: 291 / 828
Polymer Combination: 292 / 828
Polymer Combination: 293 / 828
Polymer Combination: 294 / 828
Polymer Combination: 295 / 828
Polymer Combination: 296 / 828
Polymer Combination: 297 / 828
Polymer Combination: 298 / 828
Polymer Combination: 299 / 828
Polymer Combination: 300 / 828
Polymer Combination: 301 / 828
Polymer Combination: 302 / 828
Polymer Combination: 303 / 828
Polymer Combination: 304 / 828
Polymer Combination: 305 / 828
Polymer Combination: 306 / 828
Polymer Combination: 307 / 828
Polymer Combination: 308 / 828
Polymer Combination: 309 / 828
Polymer Combination: 310 / 828
Polymer Combination: 311 / 828
Polymer Combination: 312 / 828
Polymer Combination: 313 / 828
Polymer Combination: 314 / 828
Polymer Combination: 315 / 828
Polymer Combination: 316 / 828
Polymer Combination: 317 / 828
Polymer Combination: 318 / 828
Polymer Combination: 319 / 828
Polymer Combination: 320 / 828
Polymer Combination: 321 / 828
Polymer Combination: 322 / 828
Polymer Combination: 323 / 828
Polymer Combination: 324 / 828
Polymer Combination: 325 / 828
Polymer Combination: 326 / 828
Polymer Combination: 327 / 828
Polymer Combination: 328 / 828
Polymer Combination: 329 / 828
Polymer Combination: 330 / 828
Polymer Combination: 331 / 828
Polymer Combination: 332 / 828
Polymer Combination: 333 / 828
Polymer Combination: 334 / 828
Polymer Combination: 335 / 828
Polymer Combination: 336 / 828
Polymer Combination: 337 / 828
Polymer Combination: 338 / 828
Polymer Combination: 339 / 828
Polymer Combination: 340 / 828
Polymer Combination: 341 / 828
Polymer Combination: 342 / 828
Polymer Combination: 343 / 828
Polymer Combination: 344 / 828
Polymer Combination: 345 / 828
Polymer Combination: 346 / 828
Polymer Combination: 347 / 828
Polymer Combination: 348 / 828
Polymer Combination: 349 / 828
Polymer Combination: 350 / 828
Polymer Combination: 351 / 828
Polymer Combination: 352 / 828
Polymer Combination: 353 / 828
Polymer Combination: 354 / 828
Polymer Combination: 355 / 828
Polymer Combination: 356 / 828
Polymer Combination: 357 / 828
Polymer Combination: 358 / 828
Polymer Combination: 359 / 828
Polymer Combination: 360 / 828
Polymer Combination: 361 / 828
Polymer Combination: 362 / 828
Polymer Combination: 363 / 828
Polymer Combination: 364 / 828
Polymer Combination: 365 / 828
Polymer Combination: 366 / 828
Polymer Combination: 367 / 828
Polymer Combination: 368 / 828
Polymer Combination: 369 / 828
Polymer Combination: 370 / 828
Polymer Combination: 371 / 828
Polymer Combination: 372 / 828
Polymer Combination: 373 / 828
Polymer Combination: 374 / 828
Polymer Combination: 375 / 828
Polymer Combination: 376 / 828
Polymer Combination: 377 / 828
Polymer Combination: 378 / 828
Polymer Combination: 379 / 828
Polymer Combination: 380 / 828
Polymer Combination: 381 / 828
Polymer Combination: 382 / 828
Polymer Combination: 383 / 828
Polymer Combination: 384 / 828
Polymer Combination: 385 / 828
Polymer Combination: 386 / 828
Polymer Combination: 387 / 828
Polymer Combination: 388 / 828
Polymer Combination: 389 / 828
Polymer Combination: 390 / 828
Polymer Combination: 391 / 828
Polymer Combination: 392 / 828
Polymer Combination: 393 / 828
Polymer Combination: 394 / 828
Polymer Combination: 395 / 828
Polymer Combination: 396 / 828
Polymer Combination: 397 / 828
Polymer Combination: 398 / 828
Polymer Combination: 399 / 828
Polymer Combination: 400 / 828
Polymer Combination: 401 / 828
Polymer Combination: 402 / 828
Polymer Combination: 403 / 828
Polymer Combination: 404 / 828
Polymer Combination: 405 / 828
Polymer Combination: 406 / 828
Polymer Combination: 407 / 828
Polymer Combination: 408 / 828
Polymer Combination: 409 / 828
Polymer Combination: 410 / 828
Polymer Combination: 411 / 828
Polymer Combination: 412 / 828
Polymer Combination: 413 / 828
Polymer Combination: 414 / 828
Polymer Combination: 415 / 828
Polymer Combination: 416 / 828
Polymer Combination: 417 / 828
Polymer Combination: 418 / 828
Polymer Combination: 419 / 828
Polymer Combination: 420 / 828
Polymer Combination: 421 / 828
Polymer Combination: 422 / 828
Polymer Combination: 423 / 828
Polymer Combination: 424 / 828
Polymer Combination: 425 / 828
Polymer Combination: 426 / 828
Polymer Combination: 427 / 828
Polymer Combination: 428 / 828
Polymer Combination: 429 / 828
Polymer Combination: 430 / 828
Polymer Combination: 431 / 828
Polymer Combination: 432 / 828
Polymer Combination: 433 / 828
Polymer Combination: 434 / 828
Polymer Combination: 435 / 828
Polymer Combination: 436 / 828
Polymer Combination: 437 / 828
Polymer Combination: 438 / 828
Polymer Combination: 439 / 828
Polymer Combination: 440 / 828
Polymer Combination: 441 / 828
Polymer Combination: 442 / 828
Polymer Combination: 443 / 828
Polymer Combination: 444 / 828
Polymer Combination: 445 / 828
Polymer Combination: 446 / 828
Polymer Combination: 447 / 828
Polymer Combination: 448 / 828
Polymer Combination: 449 / 828
Polymer Combination: 450 / 828
Polymer Combination: 451 / 828
Polymer Combination: 452 / 828
Polymer Combination: 453 / 828
Polymer Combination: 454 / 828
Polymer Combination: 455 / 828
Polymer Combination: 456 / 828
Polymer Combination: 457 / 828
Polymer Combination: 458 / 828
Polymer Combination: 459 / 828
Polymer Combination: 460 / 828
Polymer Combination: 461 / 828
Polymer Combination: 462 / 828
Polymer Combination: 463 / 828
Polymer Combination: 464 / 828
Polymer Combination: 465 / 828
Polymer Combination: 466 / 828
Polymer Combination: 467 / 828
Polymer Combination: 468 / 828
Polymer Combination: 469 / 828
Polymer Combination: 470 / 828
Polymer Combination: 471 / 828
Polymer Combination: 472 / 828
Polymer Combination: 473 / 828
Polymer Combination: 474 / 828
Polymer Combination: 475 / 828
Polymer Combination: 476 / 828
Polymer Combination: 477 / 828
Polymer Combination: 478 / 828
Polymer Combination: 479 / 828
Polymer Combination: 480 / 828
Polymer Combination: 481 / 828
Polymer Combination: 482 / 828
Polymer Combination: 483 / 828
Polymer Combination: 484 / 828
Polymer Combination: 485 / 828
Polymer Combination: 486 / 828
Polymer Combination: 487 / 828
Polymer Combination: 488 / 828
Polymer Combination: 489 / 828
Polymer Combination: 490 / 828
Polymer Combination: 491 / 828
Polymer Combination: 492 / 828
Polymer Combination: 493 / 828
Polymer Combination: 494 / 828
Polymer Combination: 495 / 828
Polymer Combination: 496 / 828
Polymer Combination: 497 / 828
Polymer Combination: 498 / 828
Polymer Combination: 499 / 828
Polymer Combination: 500 / 828
Polymer Combination: 501 / 828
Polymer Combination: 502 / 828
Polymer Combination: 503 / 828
Polymer Combination: 504 / 828
Polymer Combination: 505 / 828
Polymer Combination: 506 / 828
Polymer Combination: 507 / 828
Polymer Combination: 508 / 828
Polymer Combination: 509 / 828
Polymer Combination: 510 / 828
Polymer Combination: 511 / 828
Polymer Combination: 512 / 828
Polymer Combination: 513 / 828
Polymer Combination: 514 / 828
Polymer Combination: 515 / 828
Polymer Combination: 516 / 828
Polymer Combination: 517 / 828
Polymer Combination: 518 / 828
Polymer Combination: 519 / 828
Polymer Combination: 520 / 828
Polymer Combination: 521 / 828
Polymer Combination: 522 / 828
Polymer Combination: 523 / 828
Polymer Combination: 524 / 828
Polymer Combination: 525 / 828
Polymer Combination: 526 / 828
Polymer Combination: 527 / 828
Polymer Combination: 528 / 828
Polymer Combination: 529 / 828
Polymer Combination: 530 / 828
Polymer Combination: 531 / 828
Polymer Combination: 532 / 828
Polymer Combination: 533 / 828
Polymer Combination: 534 / 828
Polymer Combination: 535 / 828
Polymer Combination: 536 / 828
Polymer Combination: 537 / 828
Polymer Combination: 538 / 828
Polymer Combination: 539 / 828
Polymer Combination: 540 / 828
Polymer Combination: 541 / 828
Polymer Combination: 542 / 828
Polymer Combination: 543 / 828
Polymer Combination: 544 / 828
Polymer Combination: 545 / 828
Polymer Combination: 546 / 828
Polymer Combination: 547 / 828
Polymer Combination: 548 / 828
Polymer Combination: 549 / 828
Polymer Combination: 550 / 828
Polymer Combination: 551 / 828
Polymer Combination: 552 / 828
Polymer Combination: 553 / 828
Polymer Combination: 554 / 828
Polymer Combination: 555 / 828
Polymer Combination: 556 / 828
Polymer Combination: 557 / 828
Polymer Combination: 558 / 828
Polymer Combination: 559 / 828
Polymer Combination: 560 / 828
Polymer Combination: 561 / 828
Polymer Combination: 562 / 828
Polymer Combination: 563 / 828
Polymer Combination: 564 / 828
Polymer Combination: 565 / 828
Polymer Combination: 566 / 828
Polymer Combination: 567 / 828
Polymer Combination: 568 / 828
Polymer Combination: 569 / 828
Polymer Combination: 570 / 828
Polymer Combination: 571 / 828
Polymer Combination: 572 / 828
Polymer Combination: 573 / 828
Polymer Combination: 574 / 828
Polymer Combination: 575 / 828
Polymer Combination: 576 / 828
Polymer Combination: 577 / 828
Polymer Combination: 578 / 828
Polymer Combination: 579 / 828
Polymer Combination: 580 / 828
Polymer Combination: 581 / 828
Polymer Combination: 582 / 828
Polymer Combination: 583 / 828
Polymer Combination: 584 / 828
Polymer Combination: 585 / 828
Polymer Combination: 586 / 828
Polymer Combination: 587 / 828
Polymer Combination: 588 / 828
Polymer Combination: 589 / 828
Polymer Combination: 590 / 828
Polymer Combination: 591 / 828
Polymer Combination: 592 / 828
Polymer Combination: 593 / 828
Polymer Combination: 594 / 828
Polymer Combination: 595 / 828
Polymer Combination: 596 / 828
Polymer Combination: 597 / 828
Polymer Combination: 598 / 828
Polymer Combination: 599 / 828
Polymer Combination: 600 / 828
Polymer Combination: 601 / 828
Polymer Combination: 602 / 828
Polymer Combination: 603 / 828
Polymer Combination: 604 / 828
Polymer Combination: 605 / 828
Polymer Combination: 606 / 828
Polymer Combination: 607 / 828
Polymer Combination: 608 / 828
Polymer Combination: 609 / 828
Polymer Combination: 610 / 828
Polymer Combination: 611 / 828
Polymer Combination: 612 / 828
Polymer Combination: 613 / 828
Polymer Combination: 614 / 828
Polymer Combination: 615 / 828
Polymer Combination: 616 / 828
Polymer Combination: 617 / 828
Polymer Combination: 618 / 828
Polymer Combination: 619 / 828
Polymer Combination: 620 / 828
Polymer Combination: 621 / 828
Polymer Combination: 622 / 828
Polymer Combination: 623 / 828
Polymer Combination: 624 / 828
Polymer Combination: 625 / 828
Polymer Combination: 626 / 828
Polymer Combination: 627 / 828
Polymer Combination: 628 / 828
Polymer Combination: 629 / 828
Polymer Combination: 630 / 828
Polymer Combination: 631 / 828
Polymer Combination: 632 / 828
Polymer Combination: 633 / 828
Polymer Combination: 634 / 828
Polymer Combination: 635 / 828
Polymer Combination: 636 / 828
Polymer Combination: 637 / 828
Polymer Combination: 638 / 828
Polymer Combination: 639 / 828
Polymer Combination: 640 / 828
Polymer Combination: 641 / 828
Polymer Combination: 642 / 828
Polymer Combination: 643 / 828
Polymer Combination: 644 / 828
Polymer Combination: 645 / 828
Polymer Combination: 646 / 828
Polymer Combination: 647 / 828
Polymer Combination: 648 / 828

In [20]:
df = pd.DataFrame(data=running_list[1:],columns=running_list[0])
df = df.rename(columns={col: col + '_wt' for col in flattened_full_combo})
df.insert(0, 'ID', 'ID' + (df.index + 1).astype(str))

df

,ID,class_distribution,Tma_wt,Aeg_wt,Mo_wt,Mep_wt,Ni_wt,Phe_wt,Do_wt,Bam_wt,Oct_wt,Olam_wt,Bmam_wt,Tmb_wt,monomers,SMILES,mol_distribution
0,ID1,"[10, 50, 40]",10,0,50,0,40,0,0,0,0,0,0,0,"[Tma, Mo, Ni]","[C[N+](C)(C)CCCNC(=O)C=C, C=CC(=O)N1CCOCC1, CC...","[0.06398715373187551, 0.4684700909511932, 0.46..."
1,ID2,"[10, 55, 35]",10,0,55,0,35,0,0,0,0,0,0,0,"[Tma, Mo, Ni]","[C[N+](C)(C)CCCNC(=O)C=C, C=CC(=O)N1CCOCC1, CC...","[0.06473784309939555, 0.52136273648026, 0.4138..."
2,ID3,"[10, 60, 30]",10,0,60,0,30,0,0,0,0,0,0,0,"[Tma, Mo, Ni]","[C[N+](C)(C)CCCNC(=O)C=C, C=CC(=O)N1CCOCC1, CC...","[0.06550635555466004, 0.5755111747554202, 0.35..."
3,ID4,"[10, 65, 25]",10,0,65,0,25,0,0,0,0,0,0,0,"[Tma, Mo, Ni]","[C[N+](C)(C)CCCNC(=O)C=C, C=CC(=O)N1CCOCC1, CC...","[0.06629333346479015, 0.6309606661705321, 0.30..."
4,ID5,"[10, 70, 20]",10,0,70,0,20,0,0,0,0,0,0,0,"[Tma, Mo, Ni]","[C[N+](C)(C)CCCNC(=O)C=C, C=CC(=O)N1CCOCC1, CC...","[0.06709945044125784, 0.6877586725578159, 0.24..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7026132,ID7026133,"[90, 0, 10]",90,0,0,0,0,0,0,0,0,0,5,5,"[Tma, Bmam, Tmb]","[C[N+](C)(C)CCCNC(=O)C=C, C=CC(=O)NCCCC, CC(C)...","[0.8805124490527483, 0.0643197451193003, 0.055..."
7026133,ID7026134,"[90, 0, 10]",90,0,0,0,0,0,0,0,0,0,10,0,"[Tma, Bmam]","[C[N+](C)(C)CCCNC(=O)C=C, C=CC(=O)NCCCC]","[0.8725271336951159, 0.12747286630488405]"
7026134,ID7026135,"[90, 0, 10]",90,0,0,0,0,0,0,0,0,5,0,5,"[Tma, Olam, Tmb]","[C[N+](C)(C)CCCNC(=O)C=C, CCCCCCCC/C=C\CCCCCCC...","[0.9104183369193181, 0.032540127680013874, 0.0..."
7026135,ID7026136,"[90, 0, 10]",90,0,0,0,0,0,0,0,0,5,5,0,"[Tma, Olam, Bmam]","[C[N+](C)(C)CCCNC(=O)C=C, CCCCCCCC/C=C\CCCCCCC...","[0.9018840092521299, 0.03223509415784967, 0.06..."
7026136,ID7026137,"[90, 0, 10]",90,0,0,0,0,0,0,0,0,10,0,0,"[Tma, Olam]","[C[N+](C)(C)CCCNC(=O)C=C, CCCCCCCC/C=C\CCCCCCC...","[0.9332851365700473, 0.0667148634299528]"

In [21]:
df.to_csv("polymer_combinations.csv", index=None, sep=',', mode='w')

In [22]:
# SANITY CHECK
# df['mol_distribution'].map(lambda x: sum(x)).value_counts()
# (df['monomers'].map(lambda x: len(x)) - df['SMILES'].map(lambda x: len(x))).value_counts()